/*

 SPR_ECTO.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __spr_ecto_h_INCLUDE
#define __spr_ecto_h_INCLUDE

/* Bank of tiles. */
#define SPR_ECTOBank 0
/* Start of tile array. */
extern const unsigned char SPR_ECTO[];

#endif

/* End of SPR_ECTO.H */
