/*

 TITLE_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : bkg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __title_screen_h_INCLUDE
#define __title_screen_h_INCLUDE

#define TITLE_SCREENWidth 20
#define TITLE_SCREENHeight 18
#define TITLE_SCREENBank 0

extern const unsigned char TITLE_SCREEN[];

#endif

/* End of TITLE_SCREEN.H */
